version: '3'

services:
  systemd:
    container_name: systemd
    image: docker-systemd-jammy-systemd
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - container=docker
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: 100M